mqtt:

  sensor:
  - name: "Lavastoviglie: Tensione"
    state_topic: "tele/Teckin1/SENSOR"
    value_template: "{{ value_json.ENERGY.Voltage }}"
    unit_of_measurement: "V"

  - name: "Lavastoviglie: Potenza"
    state_topic: "tele/Teckin2/SENSOR"
    value_template: "{{ value_json.ENERGY.Power }}"
    unit_of_measurement: "W"

  - name: "Lavastoviglie: Energia"
    state_topic: "tele/Teckin2/SENSOR"
    value_template: "{{ value_json['ENERGY'].Total }}"
    unit_of_measurement: "kWh"

  - name: "Lavastoviglie: Corrente"
    state_topic: "tele/Teckin2/SENSOR"
    value_template: "{{ value_json['ENERGY'].Current }}"
    unit_of_measurement: "A"

  switch:
  - name: "Lavastoviglie"
    unique_id: lavastoviglie
    state_topic: "stat/Teckin2/POWER"
    command_topic: "cmnd/Teckin2/power"
    availability_topic: "tele/Teckin2/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false
    qos: 1

automation:

  - alias: Lavastoviglie Notifica Fine Lavaggio
    id: lavastoviglie_notifica_fine_lavaggio
    trigger:
    - below: 20
      entity_id: sensor.lavastoviglie_potenza
      for:
        minutes: 50
      platform: numeric_state
    condition:
    - after: '07:00'
      before: '23:59'
      condition: time
    action:
    - data:
        message: Lavaggio terminato
        title: Lavastoviglie
      service: notify.scialla
    - data: 
        target:
        - media_player.ovunque
        message: lavastoviglie lavaggio terminato
        data: 
          type: announce
          method: spoken
      service: notify.alexa_media
    - entity_id: automation.lavastoviglie_notifica_fine_lavaggio
      service: automation.turn_off
    initial_state: false

  - alias: Lavastoviglie Attiva Notifica
    id: lavastoviglie_attiva_notifica
    initial_state: true
    trigger:
    - platform: numeric_state
      entity_id: sensor.lavastoviglie_potenza
      above: 100
    action:
    - service: automation.turn_on
      entity_id: automation.lavastoviglie_notifica_fine_lavaggio